"use client"

import Link from "next/link"
import { ArrowLeft, Download } from "lucide-react"
import { VelvetNavbar } from "../components/themed-navbars"
import VelvetBadge from "../components/velvet-badge"
import { useTheme } from "../contexts/theme-context"

export default function PlaybookPage() {
  const { colors } = useTheme()
  return <main style={{ backgroundColor: colors.background.dark, color: colors.text.primary }} className="min-h-screen"><VelvetNavbar logo="AK / Toronto" menuItems={[{ href: "/#work", label: "Work with me" }, { href: "/articles", label: "Insights" }, { href: "/#contact", label: "Contact" }]} /><section className="mx-auto grid max-w-7xl gap-14 px-6 pb-24 pt-16 md:grid-cols-[.8fr_1.2fr] md:px-10 md:pb-32 md:pt-24"><div><Link href="/" style={{ color: colors.text.muted }} className="mb-16 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.16em]"><ArrowLeft size={14} /> Back home</Link><VelvetBadge>Free guide · 2026 edition</VelvetBadge><h1 style={{ fontFamily: "Georgia, serif" }} className="mt-7 text-6xl leading-[.92] md:text-8xl">The Deal-Maker’s<br /><em style={{ color: colors.primary }}>Playbook.</em></h1><p style={{ color: colors.text.secondary }} className="mt-8 max-w-lg text-base leading-8">A free, no-fluff guide to buying or selling a business in the GTA — valuation, deal structure, diligence, and the questions that protect your downside.</p><a href="mailto:alex@thealexkouba.com?subject=Send me the Deal-Maker's Playbook" style={{ background: colors.gradients.primary, color: colors.background.dark }} className="mt-9 inline-flex items-center gap-2 px-6 py-4 text-[10px] font-bold uppercase tracking-[.18em]"><Download size={15} /> Get the playbook</a></div><div className="relative mx-auto w-full max-w-md"><div style={{ backgroundColor: colors.background.light, border: `1px solid ${colors.border}`, boxShadow: colors.shadow }} className="aspect-[.73] p-8 md:p-12"><div style={{ border: `1px solid ${colors.primary}66` }} className="flex h-full flex-col justify-between p-6 md:p-8"><div><p style={{ color: colors.primary }} className="text-[10px] font-bold uppercase tracking-[.24em]">Alex Kouba presents</p><h2 style={{ fontFamily: "Georgia, serif" }} className="mt-6 text-4xl italic">The Toronto<br />Business<br /><em style={{ color: colors.primary }}>Playbook</em></h2></div><div><p style={{ color: colors.text.muted }} className="text-xs">2026 Edition</p><p style={{ color: colors.text.muted }} className="mt-1 text-xs">9 sections · 40+ topics</p></div></div></div></div></section><section style={{ backgroundColor: colors.background.main }} className="px-6 py-20 md:px-10"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-2"><div><p style={{ color: colors.primary }} className="text-[10px] font-bold uppercase tracking-[.2em]">What’s inside</p><h2 style={{ fontFamily: "Georgia, serif" }} className="mt-4 text-4xl italic">Built from real Toronto deals.</h2></div><p style={{ color: colors.text.secondary }} className="max-w-lg text-sm leading-8">Valuation frameworks, deal structure, diligence checklists, and the questions that help owners and buyers protect their downside before the pressure is on.</p></div></section></main>
}
